#!/usr/bin/with-contenv bash

FLAGS=""

# configure `tailscale up`
if ! [ -v TAILSCALE_AUTHKEY ]; then
    echo '[!] TAILSCALE_AUTHKEY is not defined, this will print a login URL to the screen'
else
    FLAGS="${FLAGS} --authkey=${TAILSCALE_AUTHKEY}"
fi

if [ -v TAILSCALE_HOSTNAME ]; then
    FLAGS="${FLAGS} --hostname=${TAILSCALE_HOSTNAME}"
fi

if [ -v TAILSCALE_USE_SSH ]; then
    FLAGS="${FLAGS} --ssh=${TAILSCALE_USE_SSH}"
fi

if [ -v TAILSCALE_BE_EXIT_NODE ]; then
    echo '[!] acting as an exit node, you may need to approve this in the admin console'
    FLAGS="${FLAGS} --advertise-exit-node=${TAILSCALE_BE_EXIT_NODE}"
fi

if [ -v TAILSCALE_ADVERTISE_ROUTES ]; then
    echo '[!] acting as an subnet router, you may need to approve this in the admin console'
    FLAGS="${FLAGS} --advertise-routes=${TAILSCALE_ADVERTISE_ROUTES}"
fi

tailscale up $FLAGS

# configure serve or funnel
if [ -v TAILSCALE_SERVE_PORT ] && [ -v TAILSCALE_SERVE_MODE ]; then

    if [ -v TAILSCALE_FUNNEL ]; then
        tailscale funnel --bg --"${TAILSCALE_SERVE_MODE}"="${TAILSCALE_EXPOSE_PORT:-443}" "${TAILSCALE_SERVE_PORT}"
    else
        tailscale serve --bg --"${TAILSCALE_SERVE_MODE}"="${TAILSCALE_EXPOSE_PORT:-443}" "${TAILSCALE_SERVE_PORT}"
    fi
    
fi




