#!/usr/bin/with-contenv bash

## Ubuntu
if [ -f /usr/bin/apt ]; then
    echo "\
        jq \
        wget \
        iptables" >> /mod-repo-packages-to-install.list

fi
# Alpine
if [ -f /sbin/apk ]; then
    echo "\
        jq \
        wget \
        iptables" >> /mod-repo-packages-to-install.list
fi
