#!/usr/bin/with-contenv bash

set -euo pipefail

dir="$(mktemp -d)"
pushd .
cd "${dir}"

GOARCH=""

case `uname -m` in
    x86_64)
        GOARCH="amd64"
        ;;

    aarch64)
        GOARCH="arm64"
        ;;
    riscv64)
        GOARCH="riscv64"
        ;;
    *)
        echo "Unknown CPU type $(uname -m), please file a bug at https://github.com/tailscale-dev/docker-mod"
        exit 125
        ;;
esac

tarball="$(wget -qO- 'https://pkgs.tailscale.com/stable/?mode=json' | jq -r .Tarballs.${GOARCH})"
version="$(echo ${tarball} | cut -d_ -f2)"

wget "https://pkgs.tailscale.com/stable/${tarball}" -O tailscale.tgz

tar xzf tailscale.tgz

cp -vrf "tailscale_${version}_${GOARCH}"/tailscale /usr/bin/tailscale
cp -vrf "tailscale_${version}_${GOARCH}"/tailscaled /usr/sbin/tailscaled

popd
rm -rf "${dir}"
